name: AWS example workflow
on:
  push
env:
  AWS_REGION : "us-east-1"

permissions:
  id-token: write 
  contents: read    

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: frontend
            path: frontend
          - name: product-service
            path: product-service
          - name: user-service
            path: user-service
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Listing the S3 Buckets
        run: |
          aws s3 ls 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.service.name }}
        run: |
          docker build \
            -t ${{ matrix.service.name }}:latest \
            -f ${{ matrix.service.path }}/Dockerfile \
            ${{ matrix.service.path }}
